In [1]:
#install the NumPy library
! pip install numpy


[notice] A new release of pip is available: 24.1.2 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
# importing the numpy library
import numpy as np

In [7]:
# 1. Array Creation
# Create a 1D array from a Python list
array1 = np.array([1, 2, 3, 4, 5])
# Create a 2D array of zeros with shape (2, 3)
array2 = np.zeros((2, 3))
# Create a 2D array of ones with shape (3, 2)
array3 = np.ones((3, 2))
# Create a 1D array with values from 0 to 9
array4 = np.arange(10)
# Create a 1D array with 5 values evenly spaced between 0 and 1
array5 = np.linspace(0, 1, 5)

print("Array Creation:")
print("array1:", array1)
print("array2:\n", array2)
print("array3:\n", array3)
print("array4:", array4)
print("array5:", array5)

Array Creation:
array1: [1 2 3 4 5]
array2:
 [[0. 0. 0.]
 [0. 0. 0.]]
array3:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
array4: [0 1 2 3 4 5 6 7 8 9]
array5: [0.   0.25 0.5  0.75 1.  ]


In [8]:

# 2. Array Operations
# Add 10 to each element of array1
sum_array = array1 + 10
# Multiply each element of array1 by 2
product_array = array1 * 2
# Apply exponential function element-wise to array1
exp_array = np.exp(array1)
# Apply logarithm function element-wise to array1 (shifted to avoid log(0))
log_array = np.log(array1 + 1)

print("\nArray Operations:")
print("sum_array:", sum_array)
print("product_array:", product_array)
print("exp_array:", exp_array)
print("log_array:", log_array)


Array Operations:
sum_array: [11 12 13 14 15]
product_array: [ 2  4  6  8 10]
exp_array: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
log_array: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [9]:
# 3. Indexing and Slicing
# Slice elements from index 1 to 3 from array1
sub_array = array1[1:4]

print("\nIndexing and Slicing:")
print("sub_array:", sub_array)


Indexing and Slicing:
sub_array: [2 3 4]


In [10]:
# 4. Mathematical Functions
# Calculate the mean of array1
mean_val = np.mean(array1)
# Find the maximum value in array1
max_val = np.max(array1)
# Find the minimum value in array1
min_val = np.min(array1)

print("\nMathematical Functions:")
print("mean_val:", mean_val)
print("max_val:", max_val)
print("min_val:", min_val)


Mathematical Functions:
mean_val: 3.0
max_val: 5
min_val: 1


In [11]:
# 5. Linear Algebra
# Define two matrices for matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[2, 0], [1, 3]])
# Compute the dot product (matrix multiplication) of matrix1 and matrix2
dot_product = np.dot(matrix1, matrix2)
# Compute eigenvalues and eigenvectors of matrix1
eig_values, eig_vectors = np.linalg.eig(matrix1)

print("\nLinear Algebra:")
print("dot_product:\n", dot_product)
print("Eigenvalues:", eig_values)
print("Eigenvectors:\n", eig_vectors)


Linear Algebra:
dot_product:
 [[ 4  6]
 [10 12]]
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [12]:
# 6. Reshaping and Manipulation
# Reshape array4 from shape (10,) to shape (2, 5)
reshaped_array = array4.reshape((2, 5))
# Concatenate two copies of array3 along axis 1 (horizontal concatenation)
concatenated_array = np.concatenate((array3, array3), axis=1)

print("\nReshaping and Manipulation:")
print("reshaped_array:\n", reshaped_array)
print("concatenated_array:\n", concatenated_array)


Reshaping and Manipulation:
reshaped_array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
concatenated_array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:

# 7. Broadcasting
# Add a 1D array to each row of array1 (broadcasting)
broadcast_array = array1 + np.array([1, 2, 3, 4, 5])

print("\nBroadcasting:")
print("broadcast_array:", broadcast_array)


Broadcasting:
broadcast_array: [ 2  4  6  8 10]


In [14]:
# 8. Random Number Generation
# Generate a 3x4 array of random floats between 0 and 1
random_array = np.random.rand(3, 4)
# Generate a 2x3 array of random integers between 0 and 10
random_integers = np.random.randint(0, 10, size=(2, 3))

print("\nRandom Number Generation:")
print("random_array:\n", random_array)
print("random_integers:\n", random_integers)


Random Number Generation:
random_array:
 [[7.63645798e-01 2.97736649e-01 8.88109232e-01 6.85519442e-01]
 [9.45076657e-01 5.73170752e-01 8.32002116e-01 5.44768186e-01]
 [7.03644781e-02 6.30934001e-01 6.33109188e-04 5.80041557e-01]]
random_integers:
 [[9 3 7]
 [4 1 4]]
